### ISSUE TITLE
why this happen ?

### ISSUE THREAD

**Issue by chiapparinose** [jaxBCD/Ultimate-Dork#2]
how i can fix it ?

File "ultimate-dork.py", line 15, in <module>
    from lib.dork import search_engine as _seg
  File "/root/Ultimate-Dork/lib/dork.py", line 4, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by JACK-NEW-PROJECT** [comment]
You have not installed the module
type "python -m pip install fake_useragent"
